# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: 
  branches:
    include:
    - development

pool: default

steps:
- script: |
    npm install
    npm version 1.0.$(Build.BuildId)
    npm publish
  displayName: 'install and publishing'
