# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: 
  branches:
    include:
    - master

pool: prashant

steps:
- task: NodeTool@0
  displayName: 'install'
  inputs:
    versionSource: 'spec'
    versionSpec: '6.x'

- script: |
    npm pack 
    npm start
  displayName: 'Run '
